youtube_play_list: "<youtube playlist>"
data_path: "/data/podcastbuilder/files"

podcast_name: "My Podcast"
podcast_description: ""
podcast_website: "https://www.website.com"
podcast_media_server: "http://files.website.ca"
podcast_image: "http://files.website.ca/podcast.png"
podcast_language: "ru-RU"
podcast_category: ""
podcast_subcategory: ""
podcast_owner: "Joe Doe"
podcast_owner_email: "joe@doe.ca"
podcast_author: "Jane Doe"
podcast_author_email: "jane@doe.ca"

