youtube_play_list: "<youtube playlist>"
data_path: "/data/podcastbuilder/files"

podcast_name: "My Podcast"
podcast_description: ""
podcast_website: "https://www.website.com"
podcast_media_server: "http://files.website.ca"
podcast_image: "http://files.website.ca/podcast.png"
podcast_formats:
  - "apple"
  - "rss"

